### PR TITLE
chore: Bump apko to v0.20.1

### PR DESCRIPTION
**Pull request by EyeCantCU**
Bump to the latest release of apko

### CODE REVIEW

**Comment by imjasonh** [comment]
This might be a reproducibility change, possibly introduced in 0.20.0. Does the test pass if you bump to 0.20.0 instead?

**Comment by EyeCantCU** [comment]
I'll try that real fast

**Comment by EyeCantCU** [comment]
@imjasonh looks like v0.20.0 failed as well: https://github.com/chainguard-dev/terraform-provider-apko/pull/413

**Comment by imjasonh** [comment]
> @imjasonh looks like v0.20.0 failed as well: https://github.com/chainguard-dev/terraform-provider-apko/pull/413

Okay I'll see if I can find the cause in that version and we can update the expected digest in this PR

**Comment by imjasonh** [comment]
I suspect it's https://github.com/chainguard-dev/apko/pull/1353

**Pull request closed without merging**
